### ISSUE TITLE
"The Game" site section content

### ISSUE THREAD

**Issue by clarkstachio** [the-zickle-army/zickle.io#6]
Develop the text content for the "The Game" section of the site, which describes the overall "My Zickle Army" game, as well as a high-level overview of the different game components/phases.

Content will be used for issue #5 .

**Comment by clarkstachio** [comment]
Based on our discussions, our current components/phases for the game include building an army and co-op game play. "Zickles the Gathering" was mentioned as a style of play, based on "Magic the Gathering". Is the same as the co-op game play component?

**Comment by clarkstachio** [comment]
Hey Paul, not sure where you want to share the copy you create. Are you familiar with github repos and dev workflow? If so, then Sad and I will incorporate you into the workflow. If not, would you like to share on whimsical?

**Comment by pvmihalache** [comment]
Not familiar at all!
What's the background story I need to expand? Or we don't have that either?

**Comment by clarkstachio** [comment]
Okay, no problem. I need to think of the best thing for sharing, but for now do you want to share in our whimsical space? Sad and I can get the copy from there when it is time to implement. Once I get more organized I will teach you guys some github stuff if you would like.

As for the back story, I think we are leaving that up to the urban legend contest winners in issue #8. My idea is to turn the urban legend contest section into just the urban legend section once the contest is over, with the winner stories posted. I think for now we leave some mystery and say something to the effect of "There are many rumors on the origin of the Zickle, but none have been confirmed ...."
